baseurl: "/realstate-tailwind-website"
url: "https://dpandey1105.github.io"

title: "Real Estate web sitet build using Tailwind"
description: "Real Estate web sitet build using Tailwind"

theme-color: indigo

author-name: "Diwakar Pandey"